# Generated by Django 2.2.1 on 2019-10-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abenakebe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textjoke',
            name='title',
            field=models.CharField(default='tst', max_length=150),
            preserve_default=False,
        ),
    ]
