# Generated by Django 2.2.1 on 2019-10-29 06:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abenakebe', '0002_textjoke_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagejoke',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 10, 29, 6, 47, 48, 428647, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memejoke',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textjoke',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
