# Generated by Django 2.2.1 on 2019-11-04 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abenakebe', '0003_auto_20191029_0647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagejoke',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='memejoke',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='textjoke',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='imagejoke',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memejoke',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textjoke',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TextLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='abenakebe.TextJoke')),
            ],
        ),
        migrations.CreateModel(
            name='MemeLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='abenakebe.MemeJoke')),
            ],
        ),
        migrations.CreateModel(
            name='ImageLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='abenakebe.ImageJoke')),
            ],
        ),
    ]
