# Generated by Django 2.2.1 on 2020-08-27 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abenakebe', '0004_auto_20191104_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('image', models.FileField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.IntegerField(default=0)),
                ('joke_type', models.CharField(choices=[('text', 'Text'), ('meme', 'Meme'), ('image', 'Image')], max_length=10)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='JokeLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='abenakebe.Joke')),
            ],
        ),
    ]
