# Generated by Django 2.2.1 on 2020-08-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abenakebe', '0005_joke_jokelike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joke',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
